language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  - 7
  # - 7.1.4

branches:
  # - master
  # - develop
  - dist_test

# https://torounit.com/blog/2016/01/20/2176/ 途中

env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=kurudrive@gmail.com
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=kurudrive@gmail.com
    - secure: "dr02Vmh5hQ9xlQZKWVF6eMt3mM2aXkXIW5LRhNB8UcFtUasrJnINZEJty3CEAGu94d8HSEhs2cQLdoYvxvs+6DAMoXrc+LaVFXoDmoTg1ogdCoF0cyWHLYn5tul4toOCg4mzjD2y/umDcrp/p5ezq2BmhEb5eHBz+Oqp9eZyhgXm5hf3hcb5I9c0ztUMNn1tVzhab/X7i4MMvYP36ojVekJqLY4YOOwlmoaikDPfVeK8P6nvuJJtUnVPuOwlgdQXL5iNIrGpVb6WFKDtLZcIfaEjX5zCLMynpPB+HWcALBySlkLwc03JwKcBoUKah7JdgyIebcP2D/9Q6F2U8ZmZpSx1eLpPXXwI3SMcvx7T/ac7UeTguf1f6NAokCdzxccApxJk6NxdnHMlAcK54RiXvpMiOG7BTM8C9RqSGs7BNC3g29NAKutG9qn3HlTZDlx2s9iBI+IFvxX/IZmMnI2rho2l1hVSgFORl4rArAEF5LTRZgUbhdz1RCq/f0vvKHyJ1fl40kMNYKMLcTafBx44wBL9Ep4Siwg3zmILyfEOARyC32mwpSGM0ts91QjJEOitRikHKa1f27FLX6vZW0S4Qf8L7wdaqZnReIyrqO9B/BOhInJMFjVAFwMdGpMoVha4rAQ4cfT3EEVaDBVVCaLfaADRO8uwRLhyDKkOlbeGjpc="

cache:
  directories:
    - node_modules
    - .sass_cache

before_install:
  - gem install sass
  - gem install compass

# node_js:
#   - '0.8'
#   - '0.10'

before_script:
  - npm install -g gulp gulp-concat gulp-cssmin gulp-jsmin gulp-plumber gulp-rename
  - npm install

script:
  - find ./ -name '*.php'|xargs -I {} php -l {}
  - gulp compile
  - compass compile
  - cd plugins_admin/vk-admin/ && compass compile && cd ../../

after_success:
  - bash ./bin/deploy.sh
