language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1.4

branches:
  - master
  - develop

cache:
  directories:
    - node_modules
    - .sass_cache

before_install:
  - gem install ruby
  - gem install sass
  - gem install compass

node_js:
  - '0.8'
  - '0.10'

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  # - nvm install 4.2
  # - npm install gulp gulp-concat gulp-cssmin gulp-jsmin gulp-plumber gulp-rename
  - npm install
  - npm install -g gulp
  - npm install gulp gulp-concat gulp-cssmin gulp-rename gulp-jsmin gulp-plumber gulp-sass gulp-clean-css gulp-merge-media-queries gulp-autoprefixer

script:
  - find ./ -name '*.php'|xargs -I {} php -l {}
  - phpunit
  - gulp compile
  # - compass compile
  # - cd plugins_admin/vk-admin/ && compass compile && cd ../../
